name: clipsage
version: '1.0.0'
summary: Advanced Clipboard Manager with Semantic Search
description: |
  ClipSage is a modern clipboard manager that combines intelligent semantic 
  search with a clean PyQt6 interface. It automatically captures clipboard 
  content and enables AI-powered search through your clipboard history using 
  Ollama embeddings.

  Features:
  - Semantic search through clipboard history
  - Modern PyQt6 interface  
  - Support for text and images
  - Automatic content capture
  - Real-time search and preview

base: core22
grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  clipsage:
    command: bin/clipsage-wrapper
    desktop: usr/share/applications/clipsage.desktop
    plugs:
      - home
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - network
      - network-bind
      - clipboard
      - removable-media
    environment:
      QT_QPA_PLATFORMTHEME: gtk3

parts:
  clipsage:
    plugin: python
    source: .
    python-requirements:
      - requirements.txt
    build-packages:
      - build-essential
      - cmake
      - qt6-base-dev
      - qt6-tools-dev
      - pkg-config
    stage-packages:
      - qt6-base-dev
      - libqt6core6
      - libqt6gui6
      - libqt6widgets6
      - python3-pil
    override-build: |
      craftctl default
      
      # Build the C++ clipboard manager
      cd $CRAFT_PART_SRC/clipsage/backend
      mkdir -p build
      cd build
      cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$CRAFT_PART_INSTALL
      make -j$(nproc)
      cp clipboard_manager $CRAFT_PART_INSTALL/bin/
      
      # Create wrapper script
      mkdir -p $CRAFT_PART_INSTALL/bin
      cat > $CRAFT_PART_INSTALL/bin/clipsage-wrapper << 'EOF'
      #!/bin/bash
      export PYTHONPATH="$SNAP/lib/python3.10/site-packages:$PYTHONPATH"
      cd $SNAP
      exec python3 -m clipsage "$@"
      EOF
      chmod +x $CRAFT_PART_INSTALL/bin/clipsage-wrapper
      
    stage:
      - -usr/lib/python3.10/site-packages/pip*
      - -usr/lib/python3.10/site-packages/setuptools*
      - -usr/lib/python3.10/site-packages/wheel*

  desktop-file:
    plugin: dump
    source: assets/
    organize:
      clipsage.desktop: usr/share/applications/clipsage.desktop
      icon.png: usr/share/pixmaps/clipsage.png